### ISSUE TITLE
osgi.enroute.gogo.shell.provider errors on Windows

### ISSUE THREAD

**Issue by LiamTelensa** [osgi/osgi.enroute#17]
I have observed on Windows 7 and Windows 10 that using osgi.enroute.gogo.shell.provider gives Exception in thread "OSGi enRoute Gogo Shell" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path]
    at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
    at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
    at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
    at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
    at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
    at jline.AnsiWindowsTerminal.detectAnsiSupport(AnsiWindowsTerminal.java:57)
    at jline.AnsiWindowsTerminal.<init>(AnsiWindowsTerminal.java:27)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
    at jline.TerminalFactory.create(TerminalFactory.java:102)
    at jline.TerminalFactory.get(TerminalFactory.java:186)
    at jline.TerminalFactory.get(TerminalFactory.java:192)
    at osgi.enroute.gogo.shell.provider.Shell$1.run(Shell.java:153)
    at java.lang.Thread.run(Unknown Source)

On my system jansi in the Karaf distribution works without problem.

**Comment by swimmesberger** [comment]
Have the same error on windows. Some news on this?

**Comment by odesiuz** [comment]
Use the **org.apache.felix.gogo.shell** repo
This should work for windows 10
