### ISSUE TITLE
IoT tutorial -> Crash

### ISSUE THREAD

**Issue by JSlain** [osgi/osgi.enroute#19]
I'm trying the IoT tutorial, and maybe there's something I'm doing wrong, but it crashes at the `Remote Debugging` step at this page http://enroute.osgi.org/tutorial_iot/120-exploring.html

Also, the command `sudo bndremote -a` won't work, i guess you made a bash script to encapsulate the whole command?

The exception occurs at the moment I start the debugging in eclipse to connect to the raspberry pi.

> pi@raspberrypi:~ $ sudo java -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -jar bndremote.jar -a
> Listening for transport dt_socket at address: 1044
> java.lang.InterruptedException
>         at java.lang.Object.wait(Native Method)
>         at aQute.remote.util.Link.waitForResult(Link.java:296)
>         at aQute.remote.util.Link$1.invoke(Link.java:136)
>         at com.sun.proxy.$Proxy2.getFile(Unknown Source)
>         at aQute.remote.main.EnvoyDispatcher$1.get(EnvoyDispatcher.java:200)
>         at aQute.libg.shacache.ShaCache.getFile(ShaCache.java:136)
>         at aQute.remote.main.EnvoyDispatcher$EnvoyImpl.create(EnvoyDispatcher.java:141)
>         at aQute.remote.main.EnvoyDispatcher$EnvoyImpl.createFramework(EnvoyDispatcher.java:114)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at aQute.remote.util.Link.executeCommand(Link.java:335)
>         at aQute.remote.util.Link$2.run(Link.java:173)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
>

**Comment by pkriens** [comment]
I am a bit busy at the moment but it is on my list to look into this. I did test it on my local system and that worked. What Raspberry model are you using?

**Comment by JSlain** [comment]
It's a model 2B.
In the meantime, i've checkoutted bnd and i'll try to debug bndremote in
local.


/**
 * *Ghislain Nadeau*
 * Développeur Java
 * SSQ Groupe Financier
 * nadeau.ghislain@gmail.com
 */

**Comment by JSlain** [comment]
Everything's also working fine directly on my pc. I think something happens in the transfer of the files.
Don't know what i changed, the the stacktrace is not the same now. It still crash though.

`java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at aQute.remote.util.Link.waitForResult(Link.java:296)
        at aQute.remote.util.Link$1.invoke(Link.java:136)
        at com.sun.proxy.$Proxy3.getFile(Unknown Source)
        at aQute.remote.agent.AgentServer$2.get(AgentServer.java:561)
        at aQute.libg.shacache.ShaCache.getStream(ShaCache.java:63)
        at aQute.remote.agent.AgentServer.update(AgentServer.java:267)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at aQute.remote.util.Link.executeCommand(Link.java:335)
        at aQute.remote.util.Link$2.run(Link.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Module has been uninstalled.
        at org.eclipse.osgi.container.Module.checkValid(Module.java:526)
        at org.eclipse.osgi.container.Module.start(Module.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
        at aQute.remote.agent.AgentServer.update(AgentServer.java:313)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at aQute.remote.util.Link.executeCommand(Link.java:335)
        at aQute.remote.util.Link$2.run(Link.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by JSlain** [comment]
I've reached this point in my journey to find outwhat's going on.

EnvoyDispatcher.java
```
			@Override
			public InputStream get(String sha) throws Exception {
				byte[] data = remote.getFile(sha); // <-- Always returns null
				if (data == null)
					return null;

				return new ByteArrayInputStream(data);
			}
```

Seems like some security issue between mycomputerand the agent.
Still searching.

**Comment by JSlain** [comment]
Eclipse logs (from the client side):

```
java.lang.NullPointerException
        at com.sun.proxy.$Proxy28.createFramework(Unknown Source)
        at aQute.remote.plugin.RunSessionImpl.installFramework(RunSessionImpl.java:133)
        at aQute.remote.plugin.RunSessionImpl.launch(RunSessionImpl.java:99)
        at bndtools.launch.bnd.LaunchThread.run(LaunchThread.java:100)
```

**Comment by pkriens** [comment]
If you have an actual workspace I can have a look. It seems impossible at first glance to get an NPE at that position …

Kind regards,

	Peter Kriens

**Comment by JSlain** [comment]
While trying to debug bnd, i installed up-to-date bndtools from here:

https://bndtools.ci.cloudbees.com/job/bndtools.master/lastSuccessfulBuild/artifact/build/generated/p2/

... which is 3.4.0.DEV

I also had trouble starting bndtools in debug, but thatr's another story.
However, the IoT tutorial is now working with this version of bndtools.
I used 3.3.0.REL before.

Should i close the issue now?

**Comment by pkriens** [comment]
If it works for you then I would not spend more time on it. It is always nice to know the root cause so it can be fixed but I understand that finding such a root cause can take time.

Kind regards,

	Peter Kriens

**Comment by JSlain** [comment]
Right, except i had to install another version of bndtools as the one stated in the tutorial to get it working.
I'll close it anyway.
