### ISSUE TITLE
Quickstart example fails with Java>1.8

### ISSUE THREAD

**Issue by dmm9** [osgi/osgi.enroute#206]
Related to #191, but I cannot reopen that issue.

Building the quickstart example succeeds. But when running the jar, several OSGI errors appear due to several unresolved Import-Packages. At the end, it traces down to the fact that all the `javax.*` packages were removed from the JDK between version 1.8 and version 11. So, any modern JDK will fail to run.

I am working on a PR.

```sh
! Failed to start bundle org.osgi.enroute.examples.quickstart.rest-0.0.2.202309181042, exception Could not resolve module: org.osgi.enroute.examples.quickstart.rest [14]
  Unresolved requirement: Require-Capability: osgi.contract; osgi.contract="JavaJAXRS"; filter:="(&(osgi.contract=JavaJAXRS)(version=2.1.0))"
    -> Provide-Capability: osgi.contract; version:List<Version>="2.1.0,2.0.0,1.1.0"; osgi.contract="JavaJAXRS"; uses:="javax.ws.rs,javax.ws.rs.client,javax.ws.rs.container,javax.ws.rs.core,javax.ws.rs.ext,javax.ws.rs.sse"
       org.apache.aries.javax.jax.rs-api [3]
         Unresolved requirement: Import-Package: org.apache.geronimo.osgi.registry.api; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.bind.annotation
  Unresolved requirement: Import-Package: javax.ws.rs
    -> Export-Package: javax.ws.rs; bundle-symbolic-name="org.apache.aries.javax.jax.rs-api"; bundle-version="1.0.4"; version="2.1.0"; uses:="javax.ws.rs.core"
  Unresolved requirement: Require-Capability: osgi.implementation; filter:="(&(osgi.implementation=osgi.jaxrs)(version>=1.0.0)(!(version>=2.0.0)))"
    -> Provide-Capability: osgi.implementation; version:Version="1.0.0"; osgi.implementation="osgi.jaxrs"; uses:="javax.ws.rs,javax.ws.rs.core,javax.ws.rs.ext,javax.ws.rs.client,javax.ws.rs.container,javax.ws.rs.sse,org.osgi.service.jaxrs.whiteboard"
       org.apache.aries.jax.rs.whiteboard [10]
         Unresolved requirement: Import-Package: javax.activation

org.osgi.framework.BundleException: Could not resolve module: org.osgi.enroute.examples.quickstart.rest [14]
  Unresolved requirement: Require-Capability: osgi.contract; osgi.contract="JavaJAXRS"; filter:="(&(osgi.contract=JavaJAXRS)(version=2.1.0))"
    -> Provide-Capability: osgi.contract; version:List<Version>="2.1.0,2.0.0,1.1.0"; osgi.contract="JavaJAXRS"; uses:="javax.ws.rs,javax.ws.rs.client,javax.ws.rs.container,javax.ws.rs.core,javax.ws.rs.ext,javax.ws.rs.sse"
       org.apache.aries.javax.jax.rs-api [3]
         Unresolved requirement: Import-Package: org.apache.geronimo.osgi.registry.api; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.bind.annotation
  Unresolved requirement: Import-Package: javax.ws.rs
    -> Export-Package: javax.ws.rs; bundle-symbolic-name="org.apache.aries.javax.jax.rs-api"; bundle-version="1.0.4"; version="2.1.0"; uses:="javax.ws.rs.core"
  Unresolved requirement: Require-Capability: osgi.implementation; filter:="(&(osgi.implementation=osgi.jaxrs)(version>=1.0.0)(!(version>=2.0.0)))"
    -> Provide-Capability: osgi.implementation; version:Version="1.0.0"; osgi.implementation="osgi.jaxrs"; uses:="javax.ws.rs,javax.ws.rs.core,javax.ws.rs.ext,javax.ws.rs.client,javax.ws.rs.container,javax.ws.rs.sse,org.osgi.service.jaxrs.whiteboard"
       org.apache.aries.jax.rs.whiteboard [10]
         Unresolved requirement: Import-Package: javax.activation

        at org.eclipse.osgi.container.Module.start(Module.java:463)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
        at aQute.launcher.Launcher.start(Launcher.java:686)
        at aQute.launcher.Launcher.startBundles(Launcher.java:666)
        at aQute.launcher.Launcher.activate(Launcher.java:572)
        at aQute.launcher.Launcher.launch(Launcher.java:402)
        at aQute.launcher.Launcher.run(Launcher.java:184)
        at aQute.launcher.Launcher.main(Launcher.java:160)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:119)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

**Comment by juergen-albert** [comment]
@dmm9 thanks heaps for the issues in PRs you opened. Since OSGi moved to Eclipse, we haven't put much love in enroute. So thanks for bringing it back to our attention. We will look at what you have provided as soon as we are able. Please hang tight.

**Comment by chamomile93** [comment]
Hello world. 

I seem to have the same problem with this [quickstart](https://enroute.osgi.org/tutorial/020-tutorial_qs.html#running-the-application) as well. Coming from this resolved issue https://github.com/eclipse-osgi-technology/osgi.enroute/issues/219

System : 
```sh
[15:21:26]$ mvn -v
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /usr/share/apache-maven-3.9.9
Java version: 21.0.6, vendor: Ubuntu, runtime: /usr/lib/jvm/java-21-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-57-generic", arch: "amd64", family: "unix"
```
```sh
[15:24:01]$ java -version
openjdk version "21.0.6" 2025-01-21
OpenJDK Runtime Environment (build 21.0.6+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 21.0.6+7-Ubuntu-122.04.1, mixed mode, sharing)
```

1. I could package the last step with success.
2. Running the package with the following command produces an error as below.
3. I tried to open the endpoint on firefox but got a plaintext error
```sh
HTTP ERROR 404

Problem accessing /rest/upper/lower. Reason:

    Not Found
```
4. Then tried to curl it as well but got the same plaintext error.

The error  https://web.archive.org/web/20250402150440/https://ctxt.io/2/AAB4IyzZFA

-- Edit 

I tried to change `runee` java version from 1.8 to 21 according to my java version. Tried to package again but get following error  https://textbin.net/raw/lbptcpdjcj

-- Edit

For the sake of this tutorial I am switching back to jdk_1.8-431.

 -- Edit

No problem with the quickstart tutorial with jdk_1.8-431.

**Comment by timothyjward** [comment]
I think this indicates that we need to move from the old `javax` version of the whiteboard implementation to the new `jakarta` version. Finding and updating all of the dependencies in enroute to get this working with the old packages is probably not worth the effort.
